INSERT INTO dbtest.ESTADO
(DESCRIP)
VALUES('ACTIVO');

INSERT INTO dbtest.ESTADO
(DESCRIP)
VALUES('INACTIVO');

INSERT INTO dbtest.PERSONA
(APELLIDO, EMAIL, FECHA_NACIMIENTO, NOMBRE, NRODOC, TIPODOC, ESTADO_ID)
VALUES('Power', 'HomeroPower@gmail.com', '1982-01-22', 'Homero', 40343230, 'DNI', 1);

INSERT INTO dbtest.USUARIO
(NOMBREUSUARIO, PASSWORD, ESTADO_ID)
VALUES('admin', 'admin', 1);

INSERT INTO dbtest.PERSONA_USUARIO
(Persona_ID, usuarios_ID)
VALUES(1, 1);



SELECT * from dbtest.PERSONA_USUARIO